# Generated by Django 4.0.5 on 2022-10-10 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='following',
        ),
    ]
