# Generated by Django 4.0.5 on 2022-10-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_following_user_id_userfollowing_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following',
            new_name='user_id',
        ),
    ]
