# Generated by Django 4.0.5 on 2022-10-12 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0005_post_saved'),
        ('accounts', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='other_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
