# Generated by Django 4.0.5 on 2022-10-16 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notifications_other_user_notifications_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
