# Generated by Django 4.0.5 on 2022-10-14 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_remove_post_text_post_caption_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../static/image/default.png', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(null=True, upload_to='problems'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='problem',
            name='uname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
